#!/bin/sh

# --- Monitors ---
bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9
bspc monitor DVI-D-0 -d 1 2 3 4 5

# -- Global Config ---
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_follows_monitors true

bspc config normal_border_color "4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config urgent_border_color "#dd2727"
bspc config presel_feedback_color "#5e81ac"

bspc config window_gap 6
bspc config border_width 0
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config split_ratio 0.61803

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
# bspc rule -a Firefox desktop='^6'
bspc rule -a mpc-qt state=floating

export $(dbus-launch)
bspc rule -r "*"

# --- AutoStart ---
killall "sxhkd" &
killall -q wal &
killall -q polybar &
killall cleanfullscreen
# use for setting hotkeys
sxhkd &
# setxkbmap -rules evdev -model pc104 -layout us,th -option grp:alt_shift_toggle &
# swap grave tilde key to caplock
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap &
sh ~/.config/polybar/colorblocks/scripts/pywal.sh ~/Pictures/Wallpapers &
sh ~/.config/polybar/launch.sh --colorblocks &
picom --experimental-backends --config ~/.config/picom/picom.conf &
~/.config/bspwm/cleanfullscreen &
command -v firefox_playerctl_notifier &> /dev/null && firefox_playerctl_notifier &
command -v mocp_notifier &> /dev/null && mocp_notifier &

# Show pointer outside terminal
xsetroot -cursor_name left_ptr &

# Lock Screen every 60 min
xautolock -time 60 -locker "sh ~/Scripts/lock.sh"

