#!/bin/sh

playerstatus=$(playerctl -p spotifyd status)
[[ $playerstatus = 'Playing' ]] && status_symbol='契'
[[ $playerstatus = 'Paused' ]] && status_symbol=''
if [ ! $playerstatus = 'No players found' ]; then
    output=$(playerctl -p spotifyd metadata --format "$status_symbol {{ artist }}: {{ title }}")
    echo $output
else
    echo ''
fi
