#!/bin/sh

DELAY=500 # in millisec
[[ -z "$1" ]] || DELAY=$1

send_notify(){
    title=$(playerctl -p firefox metadata xesam:title)
    artist=$(playerctl -p firefox metadata xesam:artist)
    cover_img=$(playerctl -p firefox metadata mpris:artUrl | tail -c +8)
    notify-send "Firefox Player" "Title: $title\nArtist: $artist" --icon=$cover_img --urgency=low --expire-time=3000 --app-name=firefox
}

watch(){
    all_files=$(ls $HOME/.mozilla/firefox/firefox-mpris 2>/dev/null)
    while true; do
        curr_files=$(ls $HOME/.mozilla/firefox/firefox-mpris 2>/dev/null)
        [ ! "$all_files" = "$curr_files" ] && send_notify && all_files=$curr_files
        sleep $(printf %.1f "$(($DELAY))e-3")
    done
}

watch

# if [ "$1" = 'send' ]; then
#     send_notify
# else
#     command -v onchange &> /dev/null && onchange -d $DELAY $HOME/.mozilla/firefox/firefox-mpris/ -- firefox_playerctl_notifier send
#     command -v onchange &> /dev/null || watch
# fi
